"""Configuration package."""

from src.config.loader import (ROBOT_IP, DEFAULT_SPEED_BAR, DEFAULT_OPERATION_MODE,
                                SPEED_MULTIPLIER, ACCELERATION_MULTIPLIER,
                                JOINT_SPEED, JOINT_ACCELERATION,
                                CARTESIAN_LINEAR_SPEED, CARTESIAN_LINEAR_ACCELERATION,
                                CARTESIAN_ROTATIONAL_SPEED, CARTESIAN_ROTATIONAL_ACCELERATION,
                                XB_JOINT_SPEED, XB_JOINT_ACCELERATION,
                                XB_LINEAR_SPEED, XB_LINEAR_ACCELERATION,
                                LOGGER_LEVEL, LOGGER_FORMAT, LOGGER_COLORIZE, load_config)

__all__ = ['ROBOT_IP', 'DEFAULT_SPEED_BAR', 'DEFAULT_OPERATION_MODE',
           'SPEED_MULTIPLIER', 'ACCELERATION_MULTIPLIER',
           'JOINT_SPEED', 'JOINT_ACCELERATION',
           'CARTESIAN_LINEAR_SPEED', 'CARTESIAN_LINEAR_ACCELERATION',
           'CARTESIAN_ROTATIONAL_SPEED', 'CARTESIAN_ROTATIONAL_ACCELERATION',
           'XB_JOINT_SPEED', 'XB_JOINT_ACCELERATION',
           'XB_LINEAR_SPEED', 'XB_LINEAR_ACCELERATION',
           'LOGGER_LEVEL', 'LOGGER_FORMAT', 'LOGGER_COLORIZE', 'load_config']

